import BottomNav from "@/components/BottomNav";
import Header from "@/components/Header";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Sd travel",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" flex flex-col">
        <Header />
        <main>
            {children}
        </main>
        <BottomNav />
    </div>

  );
}
